[functions.staff-accounts]
verify_jwt = true

[functions.student-contact]
verify_jwt = true

[functions.paystack-links]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-payment-link]
verify_jwt = false

[functions.paystack-payment-status]
verify_jwt = false
