import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

const money = (v) => "₦" + Number(v || 0).toLocaleString("en-NG", { minimumFractionDigits: 2 });
const phone = (v) => { const d=String(v||"").replace(/\D/g,""); return d.startsWith("0")?"+234"+d.slice(1):d.startsWith("234")?"+"+d:"+"+d; };

export default function ParentPortal() {
  const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [phoneNo,setPhoneNo]=useState(""),[pin,setPin]=useState(""),[error,setError]=useState("");
  const [students,setStudents]=useState([]),[accounts,setAccounts]=useState([]),[payments,setPayments]=useState([]),[receipts,setReceipts]=useState([]);
  const [view,setView]=useState("children"),[payBusy,setPayBusy]=useState(false);
  useEffect(()=>{let mounted=true;supabase.auth.getSession().then(({data,error})=>{if(!mounted)return;if(error)setError(error.message);setSession(data.session||null);setLoading(false);});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>mounted&&setSession(s));return()=>{mounted=false;l.subscription.unsubscribe();};},[]);
  useEffect(()=>{if(!session?.user)return;(async()=>{try{const [s,a,p,r]=await Promise.all([supabase.from("students").select("id,admission_no,first_name,middle_name,last_name").order("first_name"),supabase.from("student_fee_accounts").select("id,student_id,total_amount,status,updated_at").order("updated_at",{ascending:false}),supabase.from("payments").select("id,student_id,student_fee_account_id,amount,payment_date,method,reference,status").order("payment_date",{ascending:false}),supabase.from("receipts").select("id,payment_id,receipt_number,issued_at").order("issued_at",{ascending:false})]);if(s.error)throw s.error;if(a.error)throw a.error;if(p.error)throw p.error;if(r.error)throw r.error;setStudents(s.data||[]);setAccounts(a.data||[]);setPayments(p.data||[]);setReceipts(r.data||[]);}catch(e){setError(e.message||"Unable to load records.");}})();},[session?.user?.id]);
  const paid=useMemo(()=>{const m=new Map();payments.forEach(p=>{if(["paid","successful","completed"].includes(String(p.status||"").toLowerCase()))m.set(p.student_fee_account_id,(m.get(p.student_fee_account_id)||0)+Number(p.amount||0));});return m;},[payments]);
  const balance=(sid)=>accounts.filter(a=>a.student_id===sid).reduce((n,a)=>n+Math.max(Number(a.total_amount||0)-(paid.get(a.id)||0),0),0);
  const login=async e=>{e.preventDefault();setBusy(true);setError("");try{if(!/^\d{6}$/.test(pin))throw new Error();const {data,error}=await supabase.auth.signInWithPassword({phone:phone(phoneNo),password:pin});if(error)throw error;setSession(data.session);}catch{setError("Phone number or PIN is incorrect.");}finally{setBusy(false);}};
  const pay=async s=>{const a=accounts.find(x=>x.student_id===s.id&&Math.max(Number(x.total_amount||0)-(paid.get(x.id)||0),0)>0);if(!a)return;setPayBusy(true);setError("");try{const {data,error}=await supabase.functions.invoke("paystack-links",{body:{studentId:s.id,studentFeeAccountId:a.id}});if(error)throw error;if(data?.error)throw new Error(data.error);window.location.assign(data.url);}catch(e){setError(e.message||"Unable to open payment page.");}finally{setPayBusy(false);}};
  if(loading)return <main style={css.shell}><section style={css.card}>Loading MEKA School...</section></main>;
  if(!session?.user)return <main style={css.shell}><section style={css.auth}><b style={css.brand}>MEKA School</b><h1>Parent Portal</h1><p style={css.muted}>Sign in with the phone number registered with the school and your 6-digit PIN.</p>{error&&<p style={css.err}>{error}</p>}<form onSubmit={login}><label>Phone number<input style={css.input} value={phoneNo} onChange={e=>setPhoneNo(e.target.value)} placeholder="08012345678" inputMode="tel" required/></label><label>6-digit PIN<input style={css.input} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} maxLength={6} inputMode="numeric" required/></label><button style={css.primary} disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form><div style={css.note}><b>Forgot your PIN?</b><br/>Contact the school secretary or administrator. They can reset it. Your old PIN is never displayed.</div><p style={css.note}>Parent accounts are created by the school. There is no parent self-registration.</p></section></main>;
  return <main style={css.portal}><header style={css.top}><div><b style={css.brand}>MEKA School</b><div>Parent Portal</div></div><button onClick={()=>supabase.auth.signOut()}>Sign out</button></header><div style={css.body}><nav style={css.nav}>{[["children","My Children"],["fees","Fees"],["payments","Payment History"],["receipts","Receipts"]].map(([k,l])=><button key={k} onClick={()=>setView(k)} style={view===k?css.active:css.navBtn}>{l}</button>)}</nav><section style={css.main}>{error&&<p style={css.err}>{error}</p>}{view==="children"&&<><h1>My Children</h1><p style={css.muted}>Only children linked to your parent account are shown.</p>{students.map(s=><article style={css.row} key={s.id}><div><b>{s.first_name} {s.middle_name||""} {s.last_name}</b><div style={css.muted}>{s.admission_no||"No admission number"}</div></div><div><b>{money(balance(s.id))}</b>{balance(s.id)>0&&<button disabled={payBusy} onClick={()=>pay(s)} style={css.pay}>Pay fees</button>}</div></article>)}{!students.length&&<p style={css.muted}>No children are linked to this account. Contact the school office.</p>}</>}{view==="fees"&&<><h1>Fees</h1>{students.map(s=><article style={css.row} key={s.id}><div><b>{s.first_name} {s.last_name}</b><div style={css.muted}>{s.admission_no||""}</div></div><div><b>{money(balance(s.id))}</b>{balance(s.id)>0&&<button disabled={payBusy} onClick={()=>pay(s)} style={css.pay}>Pay fees</button>}</div></article>)}</>}{view==="payments"&&<><h1>Payment History</h1>{payments.map(p=>{const s=students.find(x=>x.id===p.student_id);return <article style={css.row} key={p.id}><div><b>{s?s.first_name+" "+s.last_name:"Student"}</b><div style={css.muted}>{p.method||"Payment"} · {p.reference||"No reference"}</div></div><div><b>{money(p.amount)}</b><div style={css.muted}>{p.payment_date?new Date(p.payment_date).toLocaleDateString("en-NG"):""}</div></div></article>})}{!payments.length&&<p style={css.muted}>No payments recorded.</p>}</>}{view==="receipts"&&<><h1>Receipts</h1>{receipts.map(r=><article style={css.row} key={r.id}><div><b>{r.receipt_number||"Receipt"}</b><div style={css.muted}>{r.issued_at?new Date(r.issued_at).toLocaleDateString("en-NG"):""}</div></div></article>)}{!receipts.length&&<p style={css.muted}>No receipts available.</p>}</>}</section></div></main>;
}
const css={shell:{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"#f8fafc",fontFamily:"Inter,system-ui,sans-serif"},auth:{width:"100%",maxWidth:440,background:"#fff",padding:30,borderRadius:18,border:"1px solid #e2e8f0"},card:{padding:24},brand:{color:"#2563eb",fontWeight:800},muted:{color:"#64748b"},input:{display:"block",width:"100%",boxSizing:"border-box",padding:12,margin:"7px 0 15px",border:"1px solid #cbd5e1",borderRadius:9},primary:{width:"100%",padding:13,border:0,borderRadius:9,background:"#2563eb",color:"#fff",fontWeight:800},err:{padding:12,borderRadius:9,background:"#fef2f2",color:"#b91c1c"},note:{fontSize:13,color:"#64748b",lineHeight:1.5,marginTop:18},portal:{minHeight:"100vh",background:"#f8fafc",fontFamily:"Inter,system-ui,sans-serif"},top:{minHeight:70,padding:"0 24px",display:"flex",alignItems:"center",justifyContent:"space-between",background:"#fff",borderBottom:"1px solid #e2e8f0"},body:{maxWidth:1100,margin:"0 auto",padding:24,display:"grid",gridTemplateColumns:"200px 1fr",gap:22},nav:{background:"#fff",padding:10,borderRadius:12,border:"1px solid #e2e8f0",height:"fit-content"},navBtn:{display:"block",width:"100%",textAlign:"left",padding:11,border:0,background:"transparent"},active:{display:"block",width:"100%",textAlign:"left",padding:11,border:0,borderRadius:8,background:"#eff6ff",color:"#1d4ed8",fontWeight:800},main:{background:"#fff",padding:24,borderRadius:14,border:"1px solid #e2e8f0"},row:{display:"flex",justifyContent:"space-between",gap:16,padding:16,borderBottom:"1px solid #e2e8f0"},pay:{display:"block",marginTop:8,padding:"8px 12px",border:0,borderRadius:8,background:"#2563eb",color:"#fff"}};
